# Generated by Django 6.0.2 on 2026-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('dummy_field', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('outsource', 'Outsource')], default='new', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
