# Generated by Django 6.0.2 on 2026-02-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='dummy_field',
        ),
    ]
