# Generated by Django 6.0.2 on 2026-02-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_part_dummy_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='source',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('outsource', 'Outsource')], default='', max_length=20),
        ),
    ]
