# Generated by Django 6.0.2 on 2026-02-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_part_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Available stock quantity'),
        ),
    ]
