# Generated by Django 6.0.2 on 2026-02-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintpartissue',
            name='source',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('outsource', 'Outsource')], default='new', help_text='Source from which part is issued', max_length=20),
        ),
    ]
