# Generated by Django 6.0.2 on 2026-02-17 17:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('complaints', '0002_complaintpartissue_source'),
        ('inventory', '0003_alter_part_source'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Service Charge + Parts Cost', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_amc',
            field=models.BooleanField(default=False, help_text='Under AMC'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free service'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_warranty',
            field=models.BooleanField(default=False, help_text='Under Warranty'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolution_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Engineer service charges', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='complaint',
            name='total_parts_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total cost of parts used', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='complaintpartissue',
            name='part_cost_at_time',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Part cost at resolution time', max_digits=10),
        ),
        migrations.AddField(
            model_name='complaintpartissue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='complaintpartissue',
            name='usage_status',
            field=models.CharField(choices=[('issued', 'Issued'), ('used', 'Used/Consumed'), ('returned', 'Returned'), ('damaged', 'Damaged')], default='issued', max_length=20),
        ),
        migrations.AddField(
            model_name='complaintpartissue',
            name='used_quantity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('visit_only', 'Visit Only'), ('cancel', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintpartissue',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='complaintpartissue',
            name='source',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('outsource', 'Outsource')], default='new', max_length=20),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status'], name='complaints__status_7c8de0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['complaint_no'], name='complaints__complai_cd9d69_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintassignment',
            index=models.Index(fields=['complaint', 'engineer'], name='complaints__complai_b48d1f_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintassignment',
            index=models.Index(fields=['is_active'], name='complaints__is_acti_ff16e4_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintpartissue',
            index=models.Index(fields=['usage_status'], name='complaints__usage_s_5e05cf_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintpartissue',
            index=models.Index(fields=['part', 'usage_status'], name='complaints__part_id_d61b11_idx'),
        ),
    ]
