# Generated by Django 6.0.1 on 2026-01-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_complaint_no_complaintassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='fault_description',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='other_details',
            field=models.TextField(blank=True, default='Service Only'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='fault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='complaints.fault'),
        ),
    ]
