# Generated by Django 6.0.1 on 2026-01-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_fault_remove_complaint_fault_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='other_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
