# Generated by Django 6.0.2 on 2026-02-17 18:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('complaints', '0003_alter_complaint_options_complaint_grand_total_and_more'),
        ('inventory', '0003_alter_part_source'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintpartissue',
            name='returned_at',
            field=models.DateTimeField(blank=True, help_text='When part was returned (if returned)', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_amc',
            field=models.BooleanField(default=False, help_text='Under Annual Maintenance Contract'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free service (no charges)'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolution_remarks',
            field=models.TextField(blank=True, help_text='Remarks at time of resolution', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='When complaint was resolved', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, help_text='Engineer who resolved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('visit_only', 'Visit Only'), ('cancel', 'Cancelled'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintpartissue',
            name='part_cost_at_time',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Part cost at resolution time (snapshot)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='complaintpartissue',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Quantity issued', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='complaintpartissue',
            name='source',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('outsource', 'Outsource')], default='new', help_text='Source from which part is issued', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintpartissue',
            name='usage_status',
            field=models.CharField(choices=[('issued', 'Issued'), ('used', 'Used/Consumed'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('lost', 'Lost')], default='issued', help_text='Current status of this part', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintpartissue',
            name='used_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Quantity actually used in service', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['resolved_at'], name='complaints__resolve_8d7822_idx'),
        ),
        migrations.AddIndex(
            model_name='complaintpartissue',
            index=models.Index(fields=['assignment', 'part'], name='complaints__assignm_af3084_idx'),
        ),
    ]
